# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cfkvs < Formula
  desc "A simple command line tool for CloudFront Key Value Store"
  homepage "https://github.com/michimani/cfkvs"
  version "0.0.9"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/michimani/cfkvs/releases/download/v0.0.9/cfkvs_0.0.9_darwin_amd64.tar.gz"
      sha256 "d50c564523a452dcdc4873be1c71a350642bbf7fbc4e41a43a61ffa35c3cedb2"

      def install
        bin.install "cfkvs"
      end
    end
    on_arm do
      url "https://github.com/michimani/cfkvs/releases/download/v0.0.9/cfkvs_0.0.9_darwin_arm64.tar.gz"
      sha256 "47f6cb04ff38fce2d0a4af3e4e0c056d56f1977eaab4371c0a292af032f59650"

      def install
        bin.install "cfkvs"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/michimani/cfkvs/releases/download/v0.0.9/cfkvs_0.0.9_linux_amd64.tar.gz"
        sha256 "17e4263ec3820df811ba445550370e15a1e43a17a8f1c4c2fda98e02c900171b"

        def install
          bin.install "cfkvs"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/michimani/cfkvs/releases/download/v0.0.9/cfkvs_0.0.9_linux_arm64.tar.gz"
        sha256 "698b0d5b7cbf10940a7d6a5709d91e19183a3ee4f28fd8d9eb74f2456cb31032"

        def install
          bin.install "cfkvs"
        end
      end
    end
  end

  test do
    system "#{bin}/goreleaser -v"
  end
end
